name: Teste Google ADK Agent

on:
  push:
    branches:
      - "**"   # Dispara em qualquer branch#
  pull_request:   # Dispara em qualquer PR

jobs:
  test-adk:
    runs-on: ubuntu-latest   # Mais rápido e recomendado que Windows

    steps:
      # 1️⃣ Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configura o Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"   # versão mais estável

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install google-adk

      # 4️⃣ Executa o agente
      - name: Run Google ADK Agent
        run: |
          source venv/bin/activate
          python my_tool_agent/agent.py
